name: Automatically execute fuzz.py from GitHub actions

on: ["push"]

jobs:
  execute-fuzz:
    name: Automatically execute fuzz.py from GitHub actions
    runs-on: ubuntu-latest
    steps:
      - run: python fuzz.py
        shell: bash
