name: Automatically execute fuzz.py from GitHub actions

on: ["push"]

jobs:
  execute-fuzz:
    name: Automatically execute fuzz.py from GitHub actions
    runs-on: ubuntu-latest
    steps:
      # this Action should follow steps to set up Python build environment
      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v4
        with:
          path: "./requirements.txt"

      - run: python fuzz.py
        shell: bash
