name: Automatically execute fuzz.py from GitHub actions

on: ["push"]

jobs:
  execute-fuzz:
    name: Automatically execute fuzz.py from GitHub actions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Setup environment
        run: pip install -r requirements.txt
        shell: bash

      - name: Run fuzz.py
        run: python fuzz.py
        shell: bash
